use parkingmonitor;

CREATE TABLE Department (

    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(32) NOT NULL,
    DepartmentType ENUM("POLICE", "PARKING_AUTHORITY") NOT NULL,
	CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UpdatedAt TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    JurisdictionID INTEGER NOT NULL,
    
    FOREIGN KEY (JurisdictionID) REFERENCES Jurisdiction(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CHECK (CHAR_LENGTH(Name) >= 3),
    INDEX JurisdictionIDX(JurisdictionID)
    
);

